animations {
    enabled = true

    bezier = myBezier, 0.05, 0.8, 0.1, 1

    animation = windows, 1, 6, default
    animation = windowsOut, 1, 7, default, popin 95%
    animation = fade, 1, 7, default
    animation = workspaces, 1, 6, default, slidevert
}
