general { 
    gaps_in = 5
    gaps_out = 8

    border_size = 0

    col.active_border = rgba(33ccffee) #rgba(00ff99ee) 0deg
    col.inactive_border = rgba(595959aa)

    resize_on_border = false 

    allow_tearing = false

    layout = dwindle
}

decoration {
    rounding = 14

    active_opacity = 1.0
    inactive_opacity = 0.95

    blur {
        enabled = false
        vibrancy = 0.8
        contrast = 0.6
        size = 8
        passes = 2
        ignore_opacity = false
    }

    shadow{
        enabled = false
        sharp = false
    }
    #blurls = gtk-layer-shell
    
}

cursor {
    no_hardware_cursors = true
}
