# Auto Start Apps
$serviceDirectory = $HOME/.config/hypr/service

# Themes
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"

# Hypr services
exec-once = hyprpaper -c $serviceDirectory/hyprpaper.conf
exec-once = hypridle

# Widgets
exec-once = eww open-many side-bar notifications
