
#       • •
#  ┓┏┓┏┓┓╋┓┏┓┏
#  ┗┗ ┛┗┗┗┗┗ ┛
#

$hyprDirectory = $HOME/.config/hypr

# Environment Variables
source = $hyprDirectory/user/env.conf

# Hardware
source = $hyprDirectory/user/monitors.conf
source = $hyprDirectory/user/inputs.conf

# Colors
source = $hyprDirectory/user/colors.conf

# Apps
source = $hyprDirectory/user/apps.conf

# Design & Logic
source = $hyprDirectory/core/appearence.conf
source = $hyprDirectory/core/animations.conf
source = $hyprDirectory/core/keybinds.conf
source = $hyprDirectory/core/rules.conf
source = $hyprDirectory/core/settings.conf

# Applications
source = $hyprDirectory/core/execs.conf
source = $hyprDirectory/user/execs.conf
