--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/abuku/wallpapers/300.jpg"

-- Special
background="#0d0c09"
foreground="#d3d0bd"
cursor="#d3d0bd"

-- Colors
color0="#0d0c09"
color1="#605D46"
color2="#6D694B"
color3="#86774E"
color4="#7E8273"
color5="#9B946A"
color6="#C0B06D"
color7="#d3d0bd"
color8="#939184"
color9="#605D46"
color10="#6D694B"
color11="#86774E"
color12="#7E8273"
color13="#9B946A"
color14="#C0B06D"
color15="#d3d0bd"
