--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/abuku/wallpapers/18.jpg"

-- Special
background="#0c0c0b"
foreground="#e2d099"
cursor="#e2d099"

-- Colors
color0="#0c0c0b"
color1="#906C2B"
color2="#C5773E"
color3="#967251"
color4="#7A8458"
color5="#A99228"
color6="#A39263"
color7="#e2d099"
color8="#9e916b"
color9="#906C2B"
color10="#C5773E"
color11="#967251"
color12="#7A8458"
color13="#A99228"
color14="#A39263"
color15="#e2d099"
