# Shell variables
# Generated by 'wal'
wallpaper='/home/abuku/wallpapers/37.jpg'

# Special
background='#091927'
foreground='#c0cbc4'
cursor='#c0cbc4'

# Colors
color0='#091927'
color1='#A4584E'
color2='#AB8C79'
color3='#597A85'
color4='#3BA995'
color5='#4FAD9B'
color6='#B29885'
color7='#c0cbc4'
color8='#868e89'
color9='#A4584E'
color10='#AB8C79'
color11='#597A85'
color12='#3BA995'
color13='#4FAD9B'
color14='#B29885'
color15='#c0cbc4'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
