# Shell variables
# Generated by 'wal'
wallpaper='/home/abuku/wallpapers/7.jpg'

# Special
background='#0c0c11'
foreground='#e0e1de'
cursor='#e0e1de'

# Colors
color0='#0c0c11'
color1='#4C5C71'
color2='#3F5882'
color3='#5D7189'
color4='#75899C'
color5='#97A6AF'
color6='#B2C1C6'
color7='#e0e1de'
color8='#9c9d9b'
color9='#4C5C71'
color10='#3F5882'
color11='#5D7189'
color12='#75899C'
color13='#97A6AF'
color14='#B2C1C6'
color15='#e0e1de'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
