--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/abuku/wallpapers/29.jpg"

-- Special
background="#0a090a"
foreground="#f0d8c6"
cursor="#f0d8c6"

-- Colors
color0="#0a090a"
color1="#957560"
color2="#3E838B"
color3="#498C95"
color4="#60969B"
color5="#7AA4A2"
color6="#9FAEAB"
color7="#f0d8c6"
color8="#a8978a"
color9="#957560"
color10="#3E838B"
color11="#498C95"
color12="#60969B"
color13="#7AA4A2"
color14="#9FAEAB"
color15="#f0d8c6"
