--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/abuku/wallpapers/9.jpg"

-- Special
background="#090a0a"
foreground="#c1c1c1"
cursor="#c1c1c1"

-- Colors
color0="#090a0a"
color1="#B2291C"
color2="#B72B21"
color3="#BC5049"
color4="#8D7D83"
color5="#59A8AE"
color6="#ADBDB8"
color7="#c1c1c1"
color8="#685555"
color9="#B2291C"
color10="#B72B21"
color11="#BC5049"
color12="#8D7D83"
color13="#59A8AE"
color14="#ADBDB8"
color15="#c1c1c1"
