# Shell variables
# Generated by 'wal'
wallpaper='/home/abuku/wallpapers/18.jpg'

# Special
background='#0c0c0b'
foreground='#e2d099'
cursor='#e2d099'

# Colors
color0='#0c0c0b'
color1='#906C2B'
color2='#C5773E'
color3='#967251'
color4='#7A8458'
color5='#A99228'
color6='#A39263'
color7='#e2d099'
color8='#9e916b'
color9='#906C2B'
color10='#C5773E'
color11='#967251'
color12='#7A8458'
color13='#A99228'
color14='#A39263'
color15='#e2d099'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
